controller_list:
  - name: controller_assem
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - Joint1
      - Joint2
      - Joint3
      - Joint4
      - Joint5
      - Endeffektor_Joint