controller_list:
  - name: fake_move_assemble_controller
    type: $(arg fake_execution_type)
    joints:
      - Joint1
      - Joint2
      - Joint3
      - Joint4
initial:  # Define initial robot poses per group
  - group: move_assemble
    pose: home