// Generated by gencpp from file conveyor/SetCommand.msg
// DO NOT EDIT!


#ifndef CONVEYOR_MESSAGE_SETCOMMAND_H
#define CONVEYOR_MESSAGE_SETCOMMAND_H

#include <ros/service_traits.h>


#include <conveyor/SetCommandRequest.h>
#include <conveyor/SetCommandResponse.h>


namespace conveyor
{

struct SetCommand
{

typedef SetCommandRequest Request;
typedef SetCommandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetCommand
} // namespace conveyor


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::conveyor::SetCommand > {
  static const char* value()
  {
    return "c348f8d8cd3a80f54328aa4159009109";
  }

  static const char* value(const ::conveyor::SetCommand&) { return value(); }
};

template<>
struct DataType< ::conveyor::SetCommand > {
  static const char* value()
  {
    return "conveyor/SetCommand";
  }

  static const char* value(const ::conveyor::SetCommand&) { return value(); }
};


// service_traits::MD5Sum< ::conveyor::SetCommandRequest> should match
// service_traits::MD5Sum< ::conveyor::SetCommand >
template<>
struct MD5Sum< ::conveyor::SetCommandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::conveyor::SetCommand >::value();
  }
  static const char* value(const ::conveyor::SetCommandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::conveyor::SetCommandRequest> should match
// service_traits::DataType< ::conveyor::SetCommand >
template<>
struct DataType< ::conveyor::SetCommandRequest>
{
  static const char* value()
  {
    return DataType< ::conveyor::SetCommand >::value();
  }
  static const char* value(const ::conveyor::SetCommandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::conveyor::SetCommandResponse> should match
// service_traits::MD5Sum< ::conveyor::SetCommand >
template<>
struct MD5Sum< ::conveyor::SetCommandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::conveyor::SetCommand >::value();
  }
  static const char* value(const ::conveyor::SetCommandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::conveyor::SetCommandResponse> should match
// service_traits::DataType< ::conveyor::SetCommand >
template<>
struct DataType< ::conveyor::SetCommandResponse>
{
  static const char* value()
  {
    return DataType< ::conveyor::SetCommand >::value();
  }
  static const char* value(const ::conveyor::SetCommandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CONVEYOR_MESSAGE_SETCOMMAND_H
