controller_list:
  - name: fake_moveit_assem_controller
    type: $(arg fake_execution_type)
    joints:
      - Joint1
      - Joint2
      - Joint3
      - Joint4
      - Joint5
      - Endeffektor_Joint
initial:  # Define initial robot poses per group
  - group: moveit_assem
    pose: A1