controller_list:
  - name: fake_moveit_shift_controller
    type: $(arg fake_execution_type)
    joints:
      - Joint1
      - Joint2
      - Joint3
      - Joint4
      - Joint_Vakuumgreifer
initial:  # Define initial robot poses per group
  - group: moveit_shift
    pose: home
