robshift:
  Joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: Joint1
    pid: {p: 100.0, i: 0.01, d: 1.0}

  Joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: Joint2
    pid: {p: 1200.0, i: 0.05, d: 20.0}
    use_gravity_compensation: true  # Gravitationskompensation

  Joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: Joint3
    pid: {p: 100.0, i: 0.01, d: 1.0}

  Joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: Joint4
    pid: {p: 100.0, i: 0.01, d: 1.0}

  Joint_Vakuumgreifer_position_controller:
    type: effort_controllers/JointPositionController
    joint: Joint_Vakuumgreifer
    pid: {p: 100.0, i: 0.01, d: 1.0}

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
